### ISSUE TITLE
faketime.dll doesn't work in Websphere Windows OS

### ISSUE THREAD

**Issue by kiran4298** [faketime-java/faketime#1]
Hi,
faketime.dll and libfaketime succesffully worked in windows and Linux in Jboss application server. I am trying to use the same in Websphere where it has IBM java. The agent is not working in websphere.
Any idea how i could make it work.

**Comment by mihhail-lapushkin** [comment]
Unfortunately, I don't have the resources to make it compatible with every JVM. You will have to figure it out on your own. There probably is some difference in the API of Native Agents on IBM JVM.
I know it's C, so it's quite a challenge for Java developers to understand/run/debug it, but maybe you like challenges :)

**Comment by kiran4298** [comment]
Thanks, i am looking into the issue in websphere. the method GetMethodName in agent.c is returning the error code 112 (JVMTI_ERROR_WRONG_PHASE) and methodName as null .Will your code runs for all the runtime classes that are in rt.jar because i see that i am printing every method of all the runtime classes, not just the System class alone when i run the dll in jboss application server?. 
In websphere the System.class is not in jre/lib/rt.jar, but it is in jre\bin\compressedrefs\jclSC180\vm.jar. 
I am suspecting this could be the issue because the other methods of different classes that are printing for methodName that is being passed into GetMethodName are all returning the error code 0 (JVMTI_ERROR_NONE), so i am thinking some classes are not there by default in rt.jar in Websphere, where it could be throwing this error 112 and for other classes that are in rt.jar is not throwing error 112.


I am trying to understand the JVMTI

The other thing i am suspecting is Native Method Bind. In System class, i dont see a method called RegisterNatives. This could be causing the issue. Do you have any idea how i could register the native methods of System class of IBM JDK?

**Comment by mihhail-lapushkin** [comment]
I've asked my colleague, who used to work on a native agent about this and unfortunately he confirmed that replacing native methods is not supported on IBM:
> System::currentTimeMillis is an INL (internal native linkage) on (Open)J9, so you actually never get an event for it, even if you fixed the code to only call those methods when in the correct phase.

> tested it out, didn't get events for a few native methods on System, checked the source, and also asked the OpenJ9 team, and Dan (Heidinga) confirmed it for me

**Comment by kiran4298** [comment]
Thanks for your reply,
Please see this link, one guy had similar issue, but in this, the last feed he mentioned as below
"Some events may be sent during the primordial phase, JNI and most of JVM TI cannot be used at this time but the method and address can be save for use later"
https://community.oracle.com/thread/2414021?start=0&tstart=0

what does it mean to "address can be save for  use later"? This is how it is explain in "Native Method Bind".

**Comment by mihhail-lapushkin** [comment]
No idea :)
if developers of IBM Java confirm that it's not possible I wouldn't bother

**Comment by kiran4298** [comment]
OK Thanks.

**Comment by Maldivia** [comment]
> what does it mean to "address can be save for use later"? This is how it is explain in "Native Method Bind".

If following the spec, you're not allowed to call many of the JVMTI/JNI functions during the primordial phase (the very early initialization of the VM), but in this case Hotspot (the core of Oracle/OpenJDK) doesn't really complain about it.

The proper way to do it would be something equivalent of the following pseudo code:
```C
JNICALL callbackNativeMethodBind(jvmti_env,  jni_env, thread, method, address, new_address_ptr) {
  if (wrongPhase) {
    list.add([method, address]);
  }
  else {
    checkForCurrentTimeMillis(...)
  }
}

JNICALL callbackVMInit(jvmti_env, jni_env, thread) {
  foreach(list) {
    checkForCurrentTimeMillis(list[i].method, list[i].address);
  }
}
```

Meaning, during the primordial phase, you basically collect all the native methods and addresses in a list/array ("save for use later"), and then when VMInit event is fired, and you know you're in the correct phase to use the JNI functions, you loop over all the collected methods and addresses, and the re-register the native method at that point using the RegisterNatives JNI method.

The problem on IBM is that since currentTimeMillis is an INL, the native method bind event is never called for that method (System.nanoTime is another example of an INL method), so even if the code was updated to collect the methods/addresses discovered in the primordial phase for checking during live phase, it would still not be in that list. It would require the OpenJ9 guys to change the way it's implemented for that to happen.

**Comment by kiran4298** [comment]
Did the IBM Java Developers say, why do they have the limitation "replacing native methods is not supported on IBM"?

**Comment by Maldivia** [comment]
You can replace native methods on IBM, but not for INL methods, since they are basically never invoked.
The method invocations of those are essentially replaced with something else when the bytecode is loaded, so even if you got an event for the native bind, and replaced it with your own, it wouldn't do anything as the bytecode replacement is hardcoded inside the jvm.

**Comment by kiran4298** [comment]
Thanks a lot.

**Comment by kiran4298** [comment]
Maldivia,

Is there any other way that we could fake the time. All i have tried is byte code manipulation of System class and running it as a javagent using javassist API. This worked only when ever i call explicitly System.currentTimeMillis, not when i call new Date(), Calendar.getInstance() though Sytem.currentTimeMillis is being called inside the Date empty constructor in my application code.
I have also tried AspectJ LoadtimeWeaving, but looks like there are limitations that it can't weave the spring proxied classes where it didnt work as a complete solution for faking the time.

**Comment by Maldivia** [comment]
Yeah, those approaches doesn't really work, unless you retransform every single place in the JDK where currentTimeMillis is called, which is why this lib replaces the native implementation instead.
HotSpot actually has the same issue as J9 (IBMs JVM), since currentTimeMillis is an intrinsic method, meaning when the JIT kicks in, it no longer cares for the native method, and just use what it it hardcoded to use (which is why you have those exotic JVM args to disable JIT compilation and the intrinsic).

As for alternatives... you could always change the system time? :D

Or implement/use OS specific solutions, for instance on Windows the RunAsDate util. Or intercept the Win32 API call the IBM JVM uses for currentTimeMillis (GetSystemTimeAsFileTime) using something like Detours to hook it.

**Comment by kiran4298** [comment]
Thanks Maldivia
